const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

let hash = 'dev';
try {
  hash = execSync('git rev-parse --short HEAD', { encoding: 'utf8' }).trim();
} catch (_) {
  // not in a git repo or git not available
}

const now = new Date();
const pad = (n) => String(n).padStart(2, '0');
const buildTime = `${pad(now.getDate())}/${pad(now.getMonth() + 1)}/${now.getFullYear()} ${pad(now.getHours())}:${pad(now.getMinutes())}`;

const content = `// Auto-generated by scripts/generate-version.js — do not edit manually
export const BUILD_VERSION = '${hash}';
export const BUILD_TIME = '${buildTime}';
`;

const dir = path.join(__dirname, '..', 'src', 'environments');
if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

fs.writeFileSync(path.join(dir, 'version.ts'), content, 'utf8');
console.log(`Version generated: ${hash} @ ${buildTime}`);
